---
app_name: Redakto
entity_set_models:
- entity_set_id: codealltag
  corpus_name: CodEAlltag
  corpus_doctype: Email
  corpus_description: CodE Alltag is a German-language email corpus
  corpus_version: '2022'
  corpus_language: German
  links:
  - https://github.com/codealltag
  entity_set_labels:
  - id: ADD
    description: Address (ADD) encompasses EmailAddress (EMAIL), PhoneNumber (PHONE) and URL (URL)
    fine_grained:
    - id: EMAIL
      description: email addresses
    - id: PHONE
      description: phone numbers, including fax numbers
    - id: URL
      description: URLs, as well as other forms of domain names
  - id: DATE
    description: Date (DATE) includes all sorts of date descriptions, such as date of birth, marriage, or death, starting and ending dates of contracts, etc.
    fine_grained:
    - id: DATE
      description: dates
  - id: FID
    description: FormalIdentifier (FID) includes Password (PASS) and UniqueFormalIdentifier (UFID)
    fine_grained:
    - id: UFID
      description: user-provided supplementary artificial name for all kinds of technical appliances to represent persons (students, customers, employees, members of social security systems (SSN), authors (ORCHID), etc.), computer systems (IP addresses), or other artifacts (e.g., IBANs, DOIs)
  - id: LOC
    description: The Location (LOC) category subsumes StreetName (STREET), StreetNumber (STREETNO), ZipCode (ZIP), and CityName (CITY)
    fine_grained:
    - id: CITY
      description: stands for villages, towns, cities, larger metropolitan areas and regions smaller than a state
    - id: STREET
      description: street names
    - id: STREETNO
      description: street numbers, house numbers
    - id: ZIP
      description: zip codes
  - id: ORG
    description: The Organization (ORG) category includes all types of legal actors such as companies, brands, institutions and agencies, etc.
    fine_grained:
    - id: ORG
      description: organizations
  - id: PERSON
    description: The PERSON (PERSON) label represent linguistic references to human entities, encompassing individual male and female names as well as collective family names.
    fine_grained:
    - id: FAMILY
      description: family names
    - id: FEMALE
      description: female given names
    - id: MALE
      description: male given names
  - id: USER
    description: UserName (USER) covers all kinds of invented user names for IT systems and platforms
    fine_grained:
    - id: USER
      description: user names
  sample_texts:
  - "Herr Markus Schneider, geboren am 14. März 1980 und wohnhaft in der Hauptstraße 12 in 10115 Berlin, stellte sich am 22. Mai 2024 mit thorakalen Schmerzen in unserer Notaufnahme vor. Die Beschwerden hatten laut eigener Angabe bereits am 20. Mai begonnen. Es wurde ein akutes Koronarsyndrom in Kombination mit einer bekannten Hypertonie diagnostiziert. Die Therapie bestand aus einer sofortigen Gabe von Acetylsalicylsäure und Heparin, woraufhin eine stationäre Aufnahme erfolgte. Am 23. Mai wurde eine koronare Angiographie durchgeführt. Der Patient konnte am 27. Mai 2024 in stabilem Zustand entlassen und zur weiteren Betreuung an seinen Hausarzt, Dr. Julia Meier in der Karl-Marx-Allee 50, übergeben werden."
  - "Frau Sabrina Koch, geboren am 2. November 1972, wohnhaft im Lindenweg 8, 80331 München, berichtete über eine zunehmende Belastungsdyspnoe, die sich über mehrere Wochen entwickelt hatte. In der internistischen Abklärung wurde eine chronisch obstruktive Lungenerkrankung (COPD) im Stadium II festgestellt. Therapeutisch wurde eine bronchodilatatorische Inhalationstherapie mit Salbutamol sowie eine kurzfristige Prednisolon-Gabe eingeleitet. Nach einer klinischen Stabilisierung wurde Frau Koch am 10. April 2025 entlassen und gebeten, sich bei ihrem Lungenfacharzt, Dr. Anton Berg in der Leopoldstraße 75, zur Verlaufskontrolle vorzustellen."
  - "Herr Peter Brandt, geb. 8. August 1955, wohnhaft in der Schulstraße 23, 04109 Leipzig, suchte unsere Einrichtung aufgrund seit Monaten bestehender Rückenschmerzen auf. Eine bildgebende Diagnostik bestätigte einen Bandscheibenvorfall auf Höhe L4/L5. Es zeigten sich jedoch keine neurologischen Defizite. Wir empfahlen zunächst eine konservative Therapie bestehend aus gezielter Physiotherapie und analgetischer Medikation. Nach ambulanter Vorstellung und ausführlicher Beratung wurde Herr Brandt am 17. Juni 2025 zur weiteren Behandlung an Dr. Yvonne Schröder vom Orthopädiezentrum Leipzig überwiesen."
  - "Frau Dr. med. Hannah Reuter, geboren am 29. Juni 1975, gesetzlich versichert bei der AOK (Versichertennummer 123456789), wurde am 3. Februar 2025 wegen einer mittelgradigen depressiven Episode (ICD-10: F32.1) stationär aufgenommen. Die Patientin klagte über Antriebslosigkeit, Schlafstörungen und gedrückte Stimmungslage. Im Rahmen des Aufenthalts wurde eine antidepressive Medikation mit Sertralin eingeleitet, begleitet von kognitiver Verhaltenstherapie in Einzel- und Gruppensitzungen. Am 17. März 2025 konnte Frau Reuter in gebessertem Zustand entlassen werden. Für die Weiterbehandlung empfehlen wir eine ambulante Psychotherapie bei Herrn Dipl.-Psych. Felix Bauer in Berlin."
  - "Herr Mehmet Yildirim, geboren am 12. Januar 1984 und wohnhaft in der Sonnenallee 104, 12045 Berlin, wurde am 15. Januar 2025 aufgrund einer manifesten Alkoholabhängigkeit stationär aufgenommen. Die Entzugsbehandlung erfolgte unter engmaschiger medizinischer Überwachung. Nach erfolgreichem körperlichem Entzug und begleitender psychotherapeutischer Intervention konnte Herr Yildirim am 30. Januar 2025 entlassen werden. Als Nachsorge wird die Teilnahme an der Selbsthilfegruppe „Nüchtern leben“ in Berlin-Neukölln dringend empfohlen."
  - "Frau Anna-Lena Weiß, geboren am 19. Juli 2002, wohnhaft in der Mozartstraße 9, 68161 Mannheim, wurde am 5. April 2025 stationär in unserer psychosomatischen Klinik aufgenommen. Die Aufnahme erfolgte aufgrund einer generalisierten Angststörung (ICD-10: F41.1), die sich in dauerhafter innerer Unruhe, Konzentrationsproblemen und körperlichen Symptomen äußerte. Therapeutisch kamen sowohl Verhaltenstherapie als auch Atemtechniken und eine medikamentöse Behandlung mit Escitalopram zum Einsatz. Nach zwei Wochen stabiler Verbesserung wurde sie am 19. April 2025 entlassen und zur weiteren Behandlung an Frau Dr. Catharina Lenz vom Mannheimer Zentrum für Angststörungen übergeben."
  - "Tim-Oliver Neumann, geboren am 12. September 2010, wurde am 18. Januar 2025 im Universitätsklinikum Leipzig aufgrund einer akuten Appendizitis operativ behandelt. Die Entscheidung zur sofortigen Operation erfolgte nach positiver klinischer Untersuchung und laborchemischem Nachweis einer Entzündung. Die Appendektomie wurde minimal-invasiv durchgeführt und verlief komplikationslos. Der Patient konnte am 21. Januar 2025 in gutem Allgemeinzustand entlassen werden."
  - "Frau Heike Möller, geboren am 25. April 1963, stellte sich im Helios Klinikum München West mit rechtsseitigen Oberbauchschmerzen vor. Die Diagnostik bestätigte das Vorliegen multipler Gallensteine mit wiederholten Koliken. Am 2. Mai 2025 wurde eine laparoskopische Cholezystektomie durchgeführt. Der postoperative Verlauf gestaltete sich unauffällig. Frau Möller wurde am 5. Mai 2025 in gutem Zustand entlassen mit der Empfehlung zur Nachkontrolle bei ihrem Hausarzt, Dr. Stefan Knoll."
  - "Dr. Thomas Henke, geboren am 1. Januar 1970, wurde am 10. März 2025 in der neurochirurgischen Abteilung der Charité Berlin aufgrund eines Bandscheibenprolapses im Segment L5/S1 operiert. Die mikrochirurgische Diskektomie verlief ohne Komplikationen. Bereits am ersten postoperativen Tag zeigte sich eine deutliche Besserung der Beinschmerzen. Am 14. März 2025 konnte Herr Dr. Henke beschwerdearm nach Hause entlassen werden."
  supported_models_root_dir:
  - models
  - codealltag
  supported_models:
  - model_name: BiLSTM-CRF(+)
    model_id: bilstm-crf-plus
    model_type: NER
    model_type_description: Named Entity Recognition
    model_loading_strategy: local_disk_storage
    model_directory_name:
    - bilstm-crf-plus
    model_version: '1.0'
    model_impl: SequenceTagger
    model_system_requirements:
    - flair==0.11.1
  - model_name: deepset/gelectra-large
    model_id: deepset-gelectra-large
    model_type: NER
    model_type_description: Named Entity Recognition
    model_loading_strategy: local_disk_storage
    model_directory_name:
    - deepset
    - gelectra-large
    model_version: '1.0'
    model_impl: SequenceTagger
    model_system_requirements:
    - flair==0.11.1
  - model_name: google/mt5-base
    model_id: google-mt5-base
    model_type: NER-PG
    model_type_description: Named Entity Recognition with Pseudonym Generation
    model_loading_strategy: local_disk_storage
    model_directory_name:
    - google
    - mt5-base
    model_version: '1.0'
    model_impl: MT5ForConditionalGeneration
    model_system_requirements:
    - flair==0.11.1
- entity_set_id: german-ler
  corpus_name: German-LER
  corpus_doctype: Legal
  corpus_description: German Legal-Entity-Recognition dataset containing court decisions from 2017 and 2018
  corpus_version: '2019'
  corpus_language: German
  links:
  - https://huggingface.co/datasets/elenanereiss/german-ler
  - https://github.com/elenanereiss/Legal-Entity-Recognition
  supported_models_root_dir:
  - models
  - german-ler
  supported_models:
  - model_name: deepset/gelectra-large
    model_id: deepset-gelectra-large
    model_type: NER
    model_type_description: Named Entity Recognition
    model_loading_strategy: local_disk_storage
    model_directory_name:
    - deepset
    - gelectra-large
    model_version: '1.0'
    model_impl: SequenceTagger
    model_system_requirements:
    - flair==0.15.1